@startuml P2P - Receive Non-Disclosing

'--------------------Skin Parameters----------------------'
skinparam SequenceMessageAlign center
skinparam ArrowFontSize 8
skinparam NoteFontSize 9
skinparam Style strictuml
skinparam ArrowColor Black
skinparam ParticipantPadding 20

!define MMAPICOLOR Red
!define SWITCHAPICOLOR Orange
!define SPAPICOLOR Green
!define USSDAPICOLOR Blue
!define FPXAPICOLOR Purple

skinparam sequence {
'ParticipantBackgroundColor DodgerBlue
ParticipantFontSize 12
ActorFontSize 12
ParticipantBorderColor Black
ParticipantBackgroundColor Gainsboro
ActorBorderColor Black
ActorBackgroundColor Gainsboro
LifeLineBorderColor Black
LifeLineBackgroundColor Gray
EntityBorderColor Black
EntityBackgroundColor White
}

'----------------Constant String Values-------------------'
!$postq = "**POST/quotes**"
!$putq = "**PUT/quotes**"
!$postt = "**POST/transfers**"
!$putt = "**PUT/transfers**"
!$http202 = "**HTTP 202** (Accepted)"
!$http200 = "**HTTP 200** (OK)"
!$am = "amount"
!$amType = "amountType"
!$transAm ="transferAmount"
!$payeeRA = "payeeReceiveAmount"
!$fsp2com = "fsp2Commission"

'----------------Participant Parameters-------------------'
actor Payer order 1
participant "FSP 1" as fsp1 order 2
participant "Mojaloop" as Switch order 3
participant "FSP 2" as fsp2 order 5
actor Payee order 6

'------------------Sequence Messages----------------------'
'---------------------------------------------------------'

Payer -> fsp1: I would like Payee \n to receive 100 USD
activate fsp1
fsp1 -> Switch: $postq\n$amType=RECEIVE,\n$am=100)
activate Switch
fsp1 <-- Switch: $http202
Switch -> fsp2: $postq\n($amType=RECEIVE,\n$am=100)
activate fsp2
Switch <-- fsp2: $http202
fsp2 -> fsp2: Commission is 1 USD in\nPayee FSP for P2P
Switch <- fsp2: $putq///<ID>//\n$transAm=99 USD,\n$payeeRA=100 USD,\n$fsp2com=1 USD)
Switch --> fsp2: $http200
deactivate fsp2
fsp1 <-- Switch: $putq///<ID>//\n$transAm=99 USD,\n$payeeRA=100 USD,\n$fsp2com=1 USD)
fsp1 --> Switch: $http200
deactivate Switch 
fsp1 -> fsp1: Payer FSP keeps commission\nas fee, Payer should also pay\nfee of 1 USD
Payer <- fsp1: Transferirg 100USD to Payee \n will cost you 101 USD \n including fees        
deactivate fsp1


Payer -> fsp1: Perform Transaction
activate fsp1
fsp1 -> fsp1: Reserve 99 USD from Payer FSP\naccount to Payee FSP account
fsp1 -> Switch: $postt\n($am=99 USD)
activate Switch
fsp1 <-- Switch: $http202
Switch -> Switch: Reserve 99 USD from Payer FSP\naccount to Payee FSP account
Switch -> fsp2: $postt\n($am=99 USD)
activate fsp2
Switch <-- fsp2:  $http202
fsp2 -> fsp2: Transfer 99 USD from Switch\naccount and 1 USD from\ncomission account\nto Payee account
fsp2 -> Payee: You have received 100 USD\nfrom Payer
Switch <- fsp2: $putt///<ID>//
Switch --> fsp2: $http200
deactivate fsp2
Switch -> Switch: Commit reserved transfer
fsp1 <- Switch: $putt///<ID>//
fsp1 --> Switch: $http200
deactivate Switch
Payer <- fsp1: Transaction successful,\nyou have paid 1 USD in fee
deactivate fsp1


@enduml