version: 2.1
jobs:
  deploy-website:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.name "${GH_NAME}"
            git config --global user.email "${GH_EMAIL}"
            echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
            yarn && GIT_USER="${GH_NAME}" yarn deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only:
                - master
                - circleci-project-setup
